### ISSUE TITLE
Can you provide production files?

### ISSUE THREAD

**Issue by hualazimo7** [ConsolesandCasks/CGB-R#1]
I d like to use the oem screen, while there are only 5V output boards.
I would appreciate it if you can give an opensource production files.

**Comment by ConsolesandCasks** [comment]
I'm hesitant to release files while I'm still doing some testing but I don't have a timeline as to when I'll have that done - I may put it under an oscilloscope again this week - if I do, I'll post the files with a disclaimer about some of the issues I'm concerned about.
